name: Publish Docker

on: [push]

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          git clone https://github.com/NordicPlayground/fw-nrfconnect-nrf
          cd fw-nrfconnect-nrf
          docker build -t fw-nrfconnect-nrf-docker -f ../Dockerfile .
      - name: Push Docker Container to Registry
        run: |
          cd fw-nrfconnect-nrf
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push
