name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          git clone https://github.com/NordicPlayground/fw-nrfconnect-nrf
          cd fw-nrfconnect-nrf
          docker build -t fw-nrfconnect-nrf-docker -f ../Dockerfile .
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: coderbyheart/fw-nrfconnect-nrf-docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
