name: Publish Docker

on:
  push:
  schedule:
    - cron: "0 * * * *"

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: |
          git clone https://github.com/NordicPlayground/fw-nrfconnect-nrf
          cd fw-nrfconnect-nrf
          docker build -t fw-nrfconnect-nrf-docker -f ../Dockerfile .
      - name: Build asset_tracker application
        run: |
          docker run --name fw-nrfconnect-nrf-docker \
            --rm -v ./fw-nrfconnect-nrf:/workdir/ncs/fw-nrfconnect-nrf \
            fw-nrfconnect-nrf-docker \
            /bin/bash -c 'cd ncs/fw-nrfconnect-nrf/applications/asset_tracker; west build -p always -b nrf9160_pca20035ns'
      - name: Publish image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push coderbyheart/fw-nrfconnect-nrf-docker:latest
