name: Verify Dockerfile

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build -t agrico-nrf-connect-sdk:v2.4.0 .

      - name: Ensure nrfjprog works
        run: |
          docker run --rm agrico-nrf-connect-sdk:v2.4.0 nrfjprog -v

      - name: Ensure clang-format works
        run: |
          docker run --rm agrico-nrf-connect-sdk:v2.4.0 clang-format --version
